name: dog_pictures
description: An example project to illustrate the architecture used by Vesper

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4
  http: ^0.13.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  network_image_mock: ^2.0.1


flutter:
  uses-material-design: true
